# Generated by Django 4.1.7 on 2023-03-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RidePosting',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('point_a', models.CharField(max_length=150)),
                ('point_b', models.CharField(max_length=150)),
                ('is_offer', models.BooleanField()),
                ('seats', models.IntegerField()),
                ('bags', models.IntegerField()),
            ],
        ),
    ]
