# Generated by Django 4.1.7 on 2023-03-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rideposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideposting',
            name='creator',
            field=models.CharField(default='michael', max_length=50),
            preserve_default=False,
        ),
    ]
