# Generated by Django 4.1.7 on 2023-03-14 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rideposting_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideposting',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
