/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedProfile
 */
export interface PatchedProfile {
    /**
     * 
     * @type {number}
     * @memberof PatchedProfile
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedProfile
     */
    idUser?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedProfile
     */
    bio?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedProfile
     */
    profileimg?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedProfile
     */
    location?: string;
}

/**
 * Check if a given object implements the PatchedProfile interface.
 */
export function instanceOfPatchedProfile(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedProfileFromJSON(json: any): PatchedProfile {
    return PatchedProfileFromJSONTyped(json, false);
}

export function PatchedProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedProfile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'idUser': !exists(json, 'id_user') ? undefined : json['id_user'],
        'bio': !exists(json, 'bio') ? undefined : json['bio'],
        'profileimg': !exists(json, 'profileimg') ? undefined : json['profileimg'],
        'location': !exists(json, 'location') ? undefined : json['location'],
    };
}

export function PatchedProfileToJSON(value?: PatchedProfile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id_user': value.idUser,
        'bio': value.bio,
        'profileimg': value.profileimg,
        'location': value.location,
    };
}

