/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * 
     * @type {number}
     * @memberof Profile
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof Profile
     */
    idUser: number;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    bio?: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    profileimg?: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    location?: string;
}

/**
 * Check if a given object implements the Profile interface.
 */
export function instanceOfProfile(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "idUser" in value;

    return isInstance;
}

export function ProfileFromJSON(json: any): Profile {
    return ProfileFromJSONTyped(json, false);
}

export function ProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Profile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'idUser': json['id_user'],
        'bio': !exists(json, 'bio') ? undefined : json['bio'],
        'profileimg': !exists(json, 'profileimg') ? undefined : json['profileimg'],
        'location': !exists(json, 'location') ? undefined : json['location'],
    };
}

export function ProfileToJSON(value?: Profile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id_user': value.idUser,
        'bio': value.bio,
        'profileimg': value.profileimg,
        'location': value.location,
    };
}

