/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RidePosting model module.
 * @module model/RidePosting
 * @version 0.0.0
 */
class RidePosting {
    /**
     * Constructs a new <code>RidePosting</code>.
     * @alias module:model/RidePosting
     * @param orderId {Number} 
     * @param pointA {String} 
     * @param pointB {String} 
     * @param isOffer {Boolean} 
     * @param seats {Number} 
     * @param bags {Number} 
     * @param creator {String} 
     */
    constructor(orderId, pointA, pointB, isOffer, seats, bags, creator) { 
        
        RidePosting.initialize(this, orderId, pointA, pointB, isOffer, seats, bags, creator);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, orderId, pointA, pointB, isOffer, seats, bags, creator) { 
        obj['order_id'] = orderId;
        obj['point_a'] = pointA;
        obj['point_b'] = pointB;
        obj['is_offer'] = isOffer;
        obj['seats'] = seats;
        obj['bags'] = bags;
        obj['creator'] = creator;
    }

    /**
     * Constructs a <code>RidePosting</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RidePosting} obj Optional instance to populate.
     * @return {module:model/RidePosting} The populated <code>RidePosting</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RidePosting();

            if (data.hasOwnProperty('order_id')) {
                obj['order_id'] = ApiClient.convertToType(data['order_id'], 'Number');
            }
            if (data.hasOwnProperty('point_a')) {
                obj['point_a'] = ApiClient.convertToType(data['point_a'], 'String');
            }
            if (data.hasOwnProperty('point_b')) {
                obj['point_b'] = ApiClient.convertToType(data['point_b'], 'String');
            }
            if (data.hasOwnProperty('is_offer')) {
                obj['is_offer'] = ApiClient.convertToType(data['is_offer'], 'Boolean');
            }
            if (data.hasOwnProperty('seats')) {
                obj['seats'] = ApiClient.convertToType(data['seats'], 'Number');
            }
            if (data.hasOwnProperty('bags')) {
                obj['bags'] = ApiClient.convertToType(data['bags'], 'Number');
            }
            if (data.hasOwnProperty('creator')) {
                obj['creator'] = ApiClient.convertToType(data['creator'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RidePosting</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RidePosting</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RidePosting.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['point_a'] && !(typeof data['point_a'] === 'string' || data['point_a'] instanceof String)) {
            throw new Error("Expected the field `point_a` to be a primitive type in the JSON string but got " + data['point_a']);
        }
        // ensure the json data is a string
        if (data['point_b'] && !(typeof data['point_b'] === 'string' || data['point_b'] instanceof String)) {
            throw new Error("Expected the field `point_b` to be a primitive type in the JSON string but got " + data['point_b']);
        }
        // ensure the json data is a string
        if (data['creator'] && !(typeof data['creator'] === 'string' || data['creator'] instanceof String)) {
            throw new Error("Expected the field `creator` to be a primitive type in the JSON string but got " + data['creator']);
        }

        return true;
    }


}

RidePosting.RequiredProperties = ["order_id", "point_a", "point_b", "is_offer", "seats", "bags", "creator"];

/**
 * @member {Number} order_id
 */
RidePosting.prototype['order_id'] = undefined;

/**
 * @member {String} point_a
 */
RidePosting.prototype['point_a'] = undefined;

/**
 * @member {String} point_b
 */
RidePosting.prototype['point_b'] = undefined;

/**
 * @member {Boolean} is_offer
 */
RidePosting.prototype['is_offer'] = undefined;

/**
 * @member {Number} seats
 */
RidePosting.prototype['seats'] = undefined;

/**
 * @member {Number} bags
 */
RidePosting.prototype['bags'] = undefined;

/**
 * @member {String} creator
 */
RidePosting.prototype['creator'] = undefined;

/**
 * @member {Date} date
 */
RidePosting.prototype['date'] = undefined;






export default RidePosting;

