/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import PatchedProfile from './model/PatchedProfile';
import PatchedRidePosting from './model/PatchedRidePosting';
import Profile from './model/Profile';
import RidePosting from './model/RidePosting';
import ProfileApi from './api/ProfileApi';
import RidepostingApi from './api/RidepostingApi';
import SchemaYmlApi from './api/SchemaYmlApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenapiJsClient = require('index'); // See note below*.
* var xxxSvc = new OpenapiJsClient.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenapiJsClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenapiJsClient.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenapiJsClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The PatchedProfile model constructor.
     * @property {module:model/PatchedProfile}
     */
    PatchedProfile,

    /**
     * The PatchedRidePosting model constructor.
     * @property {module:model/PatchedRidePosting}
     */
    PatchedRidePosting,

    /**
     * The Profile model constructor.
     * @property {module:model/Profile}
     */
    Profile,

    /**
     * The RidePosting model constructor.
     * @property {module:model/RidePosting}
     */
    RidePosting,

    /**
    * The ProfileApi service constructor.
    * @property {module:api/ProfileApi}
    */
    ProfileApi,

    /**
    * The RidepostingApi service constructor.
    * @property {module:api/RidepostingApi}
    */
    RidepostingApi,

    /**
    * The SchemaYmlApi service constructor.
    * @property {module:api/SchemaYmlApi}
    */
    SchemaYmlApi
};
