/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.RidepostingApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RidepostingApi', function() {
    describe('ridepostingCreate', function() {
      it('should call ridepostingCreate successfully', function(done) {
        //uncomment below and update the code to test ridepostingCreate
        //instance.ridepostingCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ridepostingDestroy', function() {
      it('should call ridepostingDestroy successfully', function(done) {
        //uncomment below and update the code to test ridepostingDestroy
        //instance.ridepostingDestroy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ridepostingList', function() {
      it('should call ridepostingList successfully', function(done) {
        //uncomment below and update the code to test ridepostingList
        //instance.ridepostingList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ridepostingPartialUpdate', function() {
      it('should call ridepostingPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test ridepostingPartialUpdate
        //instance.ridepostingPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ridepostingRetrieve', function() {
      it('should call ridepostingRetrieve successfully', function(done) {
        //uncomment below and update the code to test ridepostingRetrieve
        //instance.ridepostingRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ridepostingUpdate', function() {
      it('should call ridepostingUpdate successfully', function(done) {
        //uncomment below and update the code to test ridepostingUpdate
        //instance.ridepostingUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
