/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.RidePosting();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RidePosting', function() {
    it('should create an instance of RidePosting', function() {
      // uncomment below and update the code to test RidePosting
      //var instance = new OpenapiJsClient.RidePosting();
      //expect(instance).to.be.a(OpenapiJsClient.RidePosting);
    });

    it('should have the property orderId (base name: "order_id")', function() {
      // uncomment below and update the code to test the property orderId
      //var instance = new OpenapiJsClient.RidePosting();
      //expect(instance).to.be();
    });

    it('should have the property pointA (base name: "point_a")', function() {
      // uncomment below and update the code to test the property pointA
      //var instance = new OpenapiJsClient.RidePosting();
      //expect(instance).to.be();
    });

    it('should have the property pointB (base name: "point_b")', function() {
      // uncomment below and update the code to test the property pointB
      //var instance = new OpenapiJsClient.RidePosting();
      //expect(instance).to.be();
    });

    it('should have the property isOffer (base name: "is_offer")', function() {
      // uncomment below and update the code to test the property isOffer
      //var instance = new OpenapiJsClient.RidePosting();
      //expect(instance).to.be();
    });

    it('should have the property seats (base name: "seats")', function() {
      // uncomment below and update the code to test the property seats
      //var instance = new OpenapiJsClient.RidePosting();
      //expect(instance).to.be();
    });

    it('should have the property bags (base name: "bags")', function() {
      // uncomment below and update the code to test the property bags
      //var instance = new OpenapiJsClient.RidePosting();
      //expect(instance).to.be();
    });

    it('should have the property creator (base name: "creator")', function() {
      // uncomment below and update the code to test the property creator
      //var instance = new OpenapiJsClient.RidePosting();
      //expect(instance).to.be();
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new OpenapiJsClient.RidePosting();
      //expect(instance).to.be();
    });

  });

}));
