export { default as Index } from "./index/Index";
export { default as Landing } from "./landing/Landing";
export { default as Login } from "./login/Login";
export { default as Register } from "./register/Register";
export { default as Password } from "./password/Password";
export { default as EmailAuth } from "./emailauth/EmailAuth";
export { default as PhoneAuth } from "./phoneauth/PhoneAuth";
export { default as Phone } from "./phone/Phone";
export { default as Profile } from "./profile/Profile";
